<?php
return [
    'en' => [
        'title' => 'About Us',
        'text1' => 'Welcome to Fancy Wheel, your go-to hub for spinning thrills, cultural discoveries, and the cozy charm of milk tea! Launched in 2023 by a spirited crew of gaming aficionados and local explorers from Chittagong, Bangladesh, we’ve crafted a vibrant online space that fuses the high-energy buzz of casino gaming with the rich tapestry of our hometown and its beloved milk tea culture.',
        'text2' => 'At Fancy Wheel, we’re obsessed with Crazy Time by Evolution Gaming – the electrifying live game show packed with spinning wheels, jaw-dropping multipliers, and heart-pounding bonus rounds. As devoted fans, we dive into strategies, share insider tips, break down live sessions, and foster a community where players of all levels can swap stories and chase that thrilling 20,000x payout in Cash Hunt or Coin Flip. Whether you’re a newbie learning the ropes or a pro mastering Pachinko, our guides, reviews, and forums are here to keep the excitement rolling.',
        'text3' => 'Beyond the virtual wheel, Fancy Wheel is your guide to the soul of Chittagong, Bangladesh’s lively port city. From the tranquil shores of Patenga Beach, where the sunset rivals a winning spin, to the cultural treasures of the Ethnological Museum, we uncover the city’s hidden gems. Savor the spicy delights of a mezban feast at local haunts, hike the scenic trails of Foy’s Lake, or lose yourself in the bustling vibrancy of New Market’s colorful stalls. We believe Chittagong’s unpredictable charm mirrors the wild twists of Crazy Time – every corner holds a new adventure.',
        'text4' => 'And what’s an adventure without a steaming cup of milk tea? In Chittagong, milk tea isn’t just a drink – it’s a way of life. From roadside stalls brewing creamy, cardamom-infused cha to trendy cafes crafting bubble tea with chewy tapioca pearls, we celebrate the city’s love affair with this comforting beverage. Our team at Fancy Wheel is just as passionate about sharing the best milk tea spots as we are about gaming. Whether it’s sipping a classic dudh cha under the shade of a banyan tree or trying innovative flavors at a modern teahouse, we weave this cherished tradition into our recommendations, inviting you to experience Chittagong’s warmth one sip at a time.',
        'text5' => 'Our mission is to connect the global gaming community with the local heartbeat of Chittagong, blending the rush of Crazy Time, the allure of the city’s hotspots, and the cozy ritual of milk tea. We’re dedicated to promoting responsible gaming, offering resources for safe play, and creating a welcoming space for all. Join our community today – whether you’re here for the wheel, the wonders of Chittagong, or the perfect cup of milk tea, Fancy Wheel is where every spin, sip, and step sparks joy.',
        'text6' => 'Reach out with your thoughts or questions at contact@fancywheel.com. Let’s spin, sip, and explore together!'
    ],
    'bn' => [
        'title' => 'আমাদের সম্পর্কে',
        'text1' => 'Fancy Wheel-এ আপনাকে স্বাগতম, স্পিনিং-এর রোমাঞ্চ, সাংস্কৃতিক আবিষ্কার এবং দুধ চায়ের আরামদায়ক আকর্ষণের জন্য এটিই আপনার গন্তব্য! ২০২৩ সালে চট্টগ্রাম, বাংলাদেশের একদল উৎসাহী গেমিং অনুরাগী এবং স্থানীয় ভ্রমণকারীদের দ্বারা শুরু হওয়া, আমরা একটি প্রাণবন্ত অনলাইন স্থান তৈরি করেছি যা ক্যাসিনো গেমিং-এর উচ্চ-শক্তির উত্তেজনাকে আমাদের জন্মস্থান এবং এর প্রিয় দুধ চায়ের সংস্কৃতির সমৃদ্ধ ট্যাপেস্ট্রির সাথে মিশিয়ে দিয়েছে।',
        'text2' => 'Fancy Wheel-এ, আমরা Evolution Gaming-এর Crazy Time – এ মুগ্ধ – এটি একটি বৈদ্যুতিক লাইভ গেম শো যা স্পিনিং হুইল, বিস্ময়কর মাল্টিপ্লায়ার এবং হৃদয়-স্পর্শী বোনাস রাউন্ডে পরিপূর্ণ। নিবেদিত অনুরাগী হিসাবে, আমরা কৌশলগুলিতে ডুব দিই, ভেতরের টিপস শেয়ার করি, লাইভ সেশনগুলি বিশ্লেষণ করি এবং এমন একটি সম্প্রদায় গড়ে তুলি যেখানে সমস্ত স্তরের খেলোয়াড়রা গল্প বিনিময় করতে পারে এবং ক্যাশ হান্ট বা কয়েন ফ্লিপে সেই রোমাঞ্চকর ২০,০০০x পেআউট অর্জনের জন্য ছুটতে পারে। আপনি একজন নবাগত হোন বা পাচিঙ্কো (Pachinko)-তে দক্ষ একজন পেশাদার, আমাদের গাইড, পর্যালোচনা এবং ফোরামগুলি উদ্দীপনা বজায় রাখতে এখানে আছে।',
        'text3' => 'ভার্চুয়াল হুইলের বাইরে, Fancy Wheel আপনাকে বাংলাদেশের প্রাণবন্ত বন্দর নগরী চট্টগ্রামের আত্মার সাথে পরিচয় করিয়ে দেয়। পতেঙ্গা সৈকতের শান্ত উপকূল থেকে, যেখানে সূর্যাস্ত একটি বিজয়ী স্পিনের সাথে পাল্লা দেয়, নৃ-তাত্ত্বিক জাদুঘরের সাংস্কৃতিক ধন পর্যন্ত, আমরা শহরের লুকানো রত্নগুলি উন্মোচন করি। স্থানীয় রেস্তোরাঁগুলিতে মেজবানের মশলাদার স্বাদ উপভোগ করুন, ফৌজ লেকের মনোরম পথে হেঁটে যান, অথবা নিউ মার্কেটের রঙিন দোকানগুলির ব্যস্ত প্রাণবন্ততায় নিজেকে হারিয়ে ফেলুন। আমরা বিশ্বাস করি চট্টগ্রামের অপ্রত্যাশিত আকর্ষণ Crazy Time -এর বন্য মোড়গুলির প্রতিচ্ছবি – প্রতিটি কোণে একটি নতুন দুঃসাহসিক কাজ অপেক্ষা করছে।',
        'text4' => 'আর দুধ চায়ের উষ্ণ কাপ ছাড়া অ্যাডভেঞ্চার কেমন? চট্টগ্রামে, দুধ চা শুধুমাত্র একটি পানীয় নয় – এটি একটি জীবনধারা। পথপাশের দোকানগুলিতে তৈরি ক্রিমযুক্ত, এলাচ-মিশ্রিত চা থেকে শুরু করে চিবানো ট্যাপিওকা মুক্তা সহ বাবল টি তৈরি করা আধুনিক ক্যাফে পর্যন্ত, আমরা এই আরামদায়ক পানীয়ের প্রতি শহরের ভালোবাসাকে উদযাপন করি। **Fancy Wheel**-এ আমাদের দল গেমিং-এর মতোই সেরা দুধ চায়ের স্থানগুলি শেয়ার করতে আগ্রহী। সেটা বটগাছের ছায়ায় বসে ক্লাসিক দুধ চা পান করা হোক বা আধুনিক চায়ের দোকানে নতুন ফ্লেভার চেষ্টা করা হোক, আমরা আমাদের সুপারিশগুলিতে এই লালিত ঐতিহ্যকে বুনে দিয়েছি, যা আপনাকে এক চুমুকে চট্টগ্রামের উষ্ণতা অনুভব করার জন্য আমন্ত্রণ জানায়।',
        'text5' => 'আমাদের লক্ষ্য হল বৈশ্বিক গেমিং সম্প্রদায়কে চট্টগ্রামের স্থানীয় হৃদস্পন্দনের সাথে সংযুক্ত করা, Crazy Time-এর তাড়াহুড়ো, শহরের হটস্পটগুলির আকর্ষণ এবং দুধ চায়ের আরামদায়ক আচারকে একত্রিত করা। আমরা দায়িত্বশীল গেমিংকে উৎসাহিত করতে, নিরাপদ খেলার জন্য সম্পদ সরবরাহ করতে এবং সকলের জন্য একটি স্বাগত জানানোর মতো স্থান তৈরি করতে নিবেদিত। আজই আমাদের কমিউনিটিতে যোগ দিন – আপনি হুইলের জন্য, চট্টগ্রামের বিস্ময়ের জন্য বা নিখুঁত এক কাপ দুধ চায়ের জন্য এখানে থাকুন না কেন, Fancy Wheel হল এমন একটি স্থান যেখানে প্রতিটি স্পিন, চুমুক এবং পদক্ষেপে আনন্দ জাগে।',
        'text6' => 'contact@fancywheel.com-এ আপনার চিন্তা বা প্রশ্ন সহ আমাদের সাথে যোগাযোগ করুন। আসুন একসাথে স্পিন করি, পান করি এবং অন্বেষণ করি!'
    ]
];
